name: "CI/CD"

on:
  push:
    branches: [main]
    paths:
      - "**.ipynb"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [main]
    paths:
      - "**.ipynb"
      - ".github/workflows/ci.yml"
  release:
    types: [created]
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@main
